// HEADER
export const SET_COLLAPSED = 'SET_IS_COLLAPSED';

// API Login
export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_LOGIN_FULFILLED = 'FETCH_LOGIN_FULFILLED';
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';

// LOAD USER
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// FORGET PASSWORD
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_FULFILLED = 'FORGET_PASSWORD_FULFILLED';
export const FORGET_PASSWORD_ERROR = 'FORGET_PASSWORD_ERROR';

// API Login
export const FETCH_SIGNUP = 'FETCH_SIGNUP';
export const FETCH_SIGNUP_FULFILLED = 'FETCH_SIGNUP_FULFILLED';
export const FETCH_SIGNUP_ERROR = 'FETCH_SIGNUP_ERROR';

// API products
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FULFILLED = 'FETCH_PRODUCTS_FULFILLED';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Logout
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// API Orders
export const FETCH_ORDERS = 'FETCH_ORDER';
export const FETCH_ORDERS_USER_FULFILLED = 'FETCH_ORDERS_USER_FULFILLED';
export const FETCH_ORDERS_USER_ERROR = 'FETCH_ORDERS_USER_ERROR';
export const FETCH_ORDER_DELETE_FULFILLED = 'FETCH_ORDER_DELETE_FULFILLED';
export const FETCH_ORDER_DELETE_ERROR = 'FETCH_ORDER_DELETE_ERROR';
export const FETCH_ORDER_CREATE_USER_FULFILLED = 'FETCH_ORDER_CREATE_USER_FULFILLED';
export const FETCH_ORDER_CREATE_USER_ERROR = 'FETCH_ORDER_CREATE_USER_ERROR';
export const FETCH_ORDERS_TODAY_FULFILLED = 'FETCH_ORDERS_TODAY_FULFILLED';
export const FETCH_ORDERS_TODAY_ERROR = 'FETCH_ORDERS_TODAY_ERROR';
export const FETCH_ORDER_DELETE_ADMIN_FULFILLED = 'FETCH_ORDER_DELETE_ADMIN_FULFILLED';
export const FETCH_ORDERS_DAY_FULFILLED = 'FETCH_ORDERS_DAY_FULFILLED';
export const FETCH_ORDERS_DAY_ERROR = 'FETCH_ORDERS_DAY_ERROR';